# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1623, 1409)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TabWidget.setObjectName("TabWidget")
        self.LaunchTab = QtWidgets.QWidget()
        self.LaunchTab.setObjectName("LaunchTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.LaunchTab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = MplWidget(self.LaunchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = MplWidget(self.LaunchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = MplWidget(self.LaunchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = MplWidget(self.LaunchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout.addWidget(self.widget_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_7 = QtWidgets.QWidget(self.LaunchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_3.addWidget(self.widget_7)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.LaunchTab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.LaunchTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.LaunchTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.LaunchTab)
        self.doubleSpinBox.setSuffix("")
        self.doubleSpinBox.setDecimals(0)
        self.doubleSpinBox.setMinimum(100.0)
        self.doubleSpinBox.setMaximum(10000.0)
        self.doubleSpinBox.setSingleStep(100.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.LaunchTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.LaunchTab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.LaunchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 2, 1, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.LaunchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.LaunchTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 2)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.TabWidget.addTab(self.LaunchTab, "")
        self.MotorTab = QtWidgets.QWidget()
        self.MotorTab.setObjectName("MotorTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.MotorTab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_6 = MplWidget(self.MotorTab)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_4.addWidget(self.widget_6, 0, 0, 1, 2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.oxidiserLabel = QtWidgets.QLabel(self.MotorTab)
        self.oxidiserLabel.setObjectName("oxidiserLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.oxidiserLabel)
        self.oxidiserComboBox = QtWidgets.QComboBox(self.MotorTab)
        self.oxidiserComboBox.setObjectName("oxidiserComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.oxidiserComboBox)
        self.fuelLabel = QtWidgets.QLabel(self.MotorTab)
        self.fuelLabel.setObjectName("fuelLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fuelLabel)
        self.fuelComboBox = QtWidgets.QComboBox(self.MotorTab)
        self.fuelComboBox.setObjectName("fuelComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fuelComboBox)
        self.fullThrottleOxidiserMassFlowRateLabel = QtWidgets.QLabel(self.MotorTab)
        self.fullThrottleOxidiserMassFlowRateLabel.setObjectName("fullThrottleOxidiserMassFlowRateLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fullThrottleOxidiserMassFlowRateLabel)
        self.fullThrottleOxidiserMassFlowRateLineEdit = QtWidgets.QLineEdit(self.MotorTab)
        self.fullThrottleOxidiserMassFlowRateLineEdit.setObjectName("fullThrottleOxidiserMassFlowRateLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fullThrottleOxidiserMassFlowRateLineEdit)
        self.fullThrottleChamberPressureLabel = QtWidgets.QLabel(self.MotorTab)
        self.fullThrottleChamberPressureLabel.setObjectName("fullThrottleChamberPressureLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.fullThrottleChamberPressureLabel)
        self.fullThrottleChamberPressureLineEdit = QtWidgets.QLineEdit(self.MotorTab)
        self.fullThrottleChamberPressureLineEdit.setObjectName("fullThrottleChamberPressureLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fullThrottleChamberPressureLineEdit)
        self.throatDiameterLabel = QtWidgets.QLabel(self.MotorTab)
        self.throatDiameterLabel.setObjectName("throatDiameterLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.throatDiameterLabel)
        self.throatDiameterLineEdit = QtWidgets.QLineEdit(self.MotorTab)
        self.throatDiameterLineEdit.setObjectName("throatDiameterLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.throatDiameterLineEdit)
        self.expansionRationLabel = QtWidgets.QLabel(self.MotorTab)
        self.expansionRationLabel.setObjectName("expansionRationLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.expansionRationLabel)
        self.expansionRationLineEdit = QtWidgets.QLineEdit(self.MotorTab)
        self.expansionRationLineEdit.setObjectName("expansionRationLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.expansionRationLineEdit)
        self.nozzleExitDiameterLabel = QtWidgets.QLabel(self.MotorTab)
        self.nozzleExitDiameterLabel.setObjectName("nozzleExitDiameterLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.nozzleExitDiameterLabel)
        self.nozzleExitDiameterLineEdit = QtWidgets.QLineEdit(self.MotorTab)
        self.nozzleExitDiameterLineEdit.setObjectName("nozzleExitDiameterLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.nozzleExitDiameterLineEdit)
        self.fuelGrainMassLabel = QtWidgets.QLabel(self.MotorTab)
        self.fuelGrainMassLabel.setObjectName("fuelGrainMassLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.fuelGrainMassLabel)
        self.fuelGrainMassLineEdit = QtWidgets.QLineEdit(self.MotorTab)
        self.fuelGrainMassLineEdit.setObjectName("fuelGrainMassLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.fuelGrainMassLineEdit)
        self.motorDryMassLabel = QtWidgets.QLabel(self.MotorTab)
        self.motorDryMassLabel.setObjectName("motorDryMassLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.motorDryMassLabel)
        self.motorDryMassLineEdit = QtWidgets.QLineEdit(self.MotorTab)
        self.motorDryMassLineEdit.setObjectName("motorDryMassLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.motorDryMassLineEdit)
        self.gridLayout_4.addLayout(self.formLayout, 1, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.oxidiserLabel_2 = QtWidgets.QLabel(self.MotorTab)
        self.oxidiserLabel_2.setObjectName("oxidiserLabel_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.oxidiserLabel_2)
        self.oxidiserComboBox_2 = QtWidgets.QComboBox(self.MotorTab)
        self.oxidiserComboBox_2.setObjectName("oxidiserComboBox_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.oxidiserComboBox_2)
        self.fuelLabel_2 = QtWidgets.QLabel(self.MotorTab)
        self.fuelLabel_2.setObjectName("fuelLabel_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fuelLabel_2)
        self.fuelComboBox_2 = QtWidgets.QComboBox(self.MotorTab)
        self.fuelComboBox_2.setObjectName("fuelComboBox_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fuelComboBox_2)
        self.fullThrottleOxidiserMassFlowRateLabel_2 = QtWidgets.QLabel(self.MotorTab)
        self.fullThrottleOxidiserMassFlowRateLabel_2.setObjectName("fullThrottleOxidiserMassFlowRateLabel_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fullThrottleOxidiserMassFlowRateLabel_2)
        self.fullThrottleOxidiserMassFlowRateLineEdit_2 = QtWidgets.QLineEdit(self.MotorTab)
        self.fullThrottleOxidiserMassFlowRateLineEdit_2.setObjectName("fullThrottleOxidiserMassFlowRateLineEdit_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fullThrottleOxidiserMassFlowRateLineEdit_2)
        self.fullThrottleChamberPressureLabel_2 = QtWidgets.QLabel(self.MotorTab)
        self.fullThrottleChamberPressureLabel_2.setObjectName("fullThrottleChamberPressureLabel_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.fullThrottleChamberPressureLabel_2)
        self.fullThrottleChamberPressureLineEdit_2 = QtWidgets.QLineEdit(self.MotorTab)
        self.fullThrottleChamberPressureLineEdit_2.setObjectName("fullThrottleChamberPressureLineEdit_2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fullThrottleChamberPressureLineEdit_2)
        self.throatDiameterLabel_2 = QtWidgets.QLabel(self.MotorTab)
        self.throatDiameterLabel_2.setObjectName("throatDiameterLabel_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.throatDiameterLabel_2)
        self.throatDiameterLineEdit_2 = QtWidgets.QLineEdit(self.MotorTab)
        self.throatDiameterLineEdit_2.setObjectName("throatDiameterLineEdit_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.throatDiameterLineEdit_2)
        self.expansionRationLabel_2 = QtWidgets.QLabel(self.MotorTab)
        self.expansionRationLabel_2.setObjectName("expansionRationLabel_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.expansionRationLabel_2)
        self.expansionRationLineEdit_2 = QtWidgets.QLineEdit(self.MotorTab)
        self.expansionRationLineEdit_2.setObjectName("expansionRationLineEdit_2")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.expansionRationLineEdit_2)
        self.nozzleExitDiameterLabel_2 = QtWidgets.QLabel(self.MotorTab)
        self.nozzleExitDiameterLabel_2.setObjectName("nozzleExitDiameterLabel_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.nozzleExitDiameterLabel_2)
        self.nozzleExitDiameterLineEdit_2 = QtWidgets.QLineEdit(self.MotorTab)
        self.nozzleExitDiameterLineEdit_2.setObjectName("nozzleExitDiameterLineEdit_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.nozzleExitDiameterLineEdit_2)
        self.fuelGrainMassLabel_2 = QtWidgets.QLabel(self.MotorTab)
        self.fuelGrainMassLabel_2.setObjectName("fuelGrainMassLabel_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.fuelGrainMassLabel_2)
        self.fuelGrainMassLineEdit_2 = QtWidgets.QLineEdit(self.MotorTab)
        self.fuelGrainMassLineEdit_2.setObjectName("fuelGrainMassLineEdit_2")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.fuelGrainMassLineEdit_2)
        self.motorDryMassLabel_2 = QtWidgets.QLabel(self.MotorTab)
        self.motorDryMassLabel_2.setObjectName("motorDryMassLabel_2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.motorDryMassLabel_2)
        self.motorDryMassLineEdit_2 = QtWidgets.QLineEdit(self.MotorTab)
        self.motorDryMassLineEdit_2.setObjectName("motorDryMassLineEdit_2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.motorDryMassLineEdit_2)
        self.gridLayout_4.addLayout(self.formLayout_2, 1, 1, 1, 1)
        self.TabWidget.addTab(self.MotorTab, "")
        self.VehicleTab = QtWidgets.QWidget()
        self.VehicleTab.setObjectName("VehicleTab")
        self.TabWidget.addTab(self.VehicleTab, "")
        self.gridLayout.addWidget(self.TabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1623, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(1)
        self.pushButton.clicked.connect(MainWindow.launchClicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "Initial Launch Velocity Y"))
        self.label_2.setText(_translate("MainWindow", "Initital Launch Velocity X"))
        self.label_4.setText(_translate("MainWindow", "Time Step"))
        self.label_5.setText(_translate("MainWindow", "%"))
        self.pushButton.setText(_translate("MainWindow", "Launch"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.LaunchTab), _translate("MainWindow", "Launch"))
        self.oxidiserLabel.setText(_translate("MainWindow", "Oxidiser"))
        self.fuelLabel.setText(_translate("MainWindow", "Fuel"))
        self.fullThrottleOxidiserMassFlowRateLabel.setText(_translate("MainWindow", "Full Throttle Oxidiser Mass Flow Rate"))
        self.fullThrottleChamberPressureLabel.setText(_translate("MainWindow", "Full Throttle Chamber Pressure"))
        self.throatDiameterLabel.setText(_translate("MainWindow", "Throat Diameter"))
        self.expansionRationLabel.setText(_translate("MainWindow", "Expansion Ratio"))
        self.nozzleExitDiameterLabel.setText(_translate("MainWindow", "Nozzle Exit Diameter"))
        self.fuelGrainMassLabel.setText(_translate("MainWindow", "Fuel Grain Mass"))
        self.motorDryMassLabel.setText(_translate("MainWindow", "Motor Dry Mass"))
        self.oxidiserLabel_2.setText(_translate("MainWindow", "Oxidiser"))
        self.fuelLabel_2.setText(_translate("MainWindow", "Fuel"))
        self.fullThrottleOxidiserMassFlowRateLabel_2.setText(_translate("MainWindow", "Full Throttle Oxidiser Mass Flow Rate"))
        self.fullThrottleChamberPressureLabel_2.setText(_translate("MainWindow", "Full Throttle Chamber Pressure"))
        self.throatDiameterLabel_2.setText(_translate("MainWindow", "Throat Diameter"))
        self.expansionRationLabel_2.setText(_translate("MainWindow", "Expansion Ratio"))
        self.nozzleExitDiameterLabel_2.setText(_translate("MainWindow", "Nozzle Exit Diameter"))
        self.fuelGrainMassLabel_2.setText(_translate("MainWindow", "Fuel Grain Mass"))
        self.motorDryMassLabel_2.setText(_translate("MainWindow", "Motor Dry Mass"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.MotorTab), _translate("MainWindow", "Motor"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.VehicleTab), _translate("MainWindow", "Vehicle"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

